fragment ListHub  on ManagementHub {
  id
  name 
  online
  lastHealthy
  organization {
    id
    name
  }
  instances {
    ...ListServiceInstance
  }
  clients {
    ...ListClient
  }
}

fragment Hub on ManagementHub {
  id
  name 
  online
  lastHealthy
  lastSeenAt
  version
  meshConnected
  meshHost
  healthSnapshots {
    id
    healthy
    createdAt
    instances {
      identifier
      healthy
      reason
    }
  }
  organization {
    id
    name
  }
  instances {
    ...ListServiceInstance
  }
  clients {
    ...ListClient
  }
}
