import { useState } from 'react'
import * as allauth from '../lib/allauth'
import { Navigate, useLoaderData, Link } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"
import { Button } from "@/components/ui/button"
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription
} from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { AlertCircle } from "lucide-react"
import { useAuth } from '@/auth'
import { useActivateTotpForm } from '@/hooks/use-next'
import { InputOTP, InputOTPGroup, InputOTPSlot } from '@/components/ui/input-otp'

export async function loader ({ params }) {
  const resp = await allauth.getTOTPAuthenticator()
  return { totp: resp }
}

const formSchema = z.object({
  code: z.string().min(1, "Authenticator code is required"),
})

export default function ActivateTOTP () {
  const { totp } = useLoaderData() as { totp: allauth.APIResponse }
  

  const { onSubmit, form, globalError } = useActivateTotpForm()
 
  if (totp.status === 409) {
    return <div className="flex justify-center items-center min-h-[50vh] p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle>TOTP Activation not possible </CardTitle>
          <CardDescription>
           {totp.errors?.map((e ) => e.message).join(" ") || 'Your account is already secured with TOTP.'}
          </CardDescription>
        </CardHeader>
        <CardFooter>
          <Button asChild>
            <Link to="/account/2fa">Go back</Link>
          </Button>
        </CardFooter>
      </Card>
    </div>
  }


  return (
    <div className="flex justify-center items-center min-h-[50vh] p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle>Activate TOTP</CardTitle>
          <CardDescription>
            Set up Two-Factor Authentication using an authenticator app.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {globalError && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{globalError}</AlertDescription>
            </Alert>
          )}


          <div className="flex flex-col items-center justify-center space-y-4">
            <div className="bg-white p-4 rounded-lg border">
                <QRCodeSVG value={totp.meta?.totp_url || ''} size={192} />
            </div>
            <div className="text-center space-y-2 w-full">
                <p className="text-sm text-muted-foreground">
                    Scan the QR code with your authenticator app.
                </p>
                <div className="space-y-1">
                    <p className="text-xs font-medium uppercase text-muted-foreground">Secret Key</p>
                    <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold block break-all">
                        {totp.meta?.secret}
                    </code>
                    <p className="text-xs text-muted-foreground">
                        You can store this secret to reinstall your authenticator app later.
                    </p>
                </div>
            </div>
          </div>

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
              <FormField
                control={form.control}
                name="code"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Authenticator Code</FormLabel>
                    <FormControl>
                     <InputOTP
        maxLength={6}
        {...field}
      >
        <InputOTPGroup>
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
          <InputOTPSlot index={3} />
          <InputOTPSlot index={4} />
          <InputOTPSlot index={5} />
        </InputOTPGroup>
      </InputOTP>
                    </FormControl>
                    <FormDescription>
                        Enter the code generated by your app.
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button type="submit" className="w-full" disabled={form.formState.isSubmitting}>
                Activate
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
    </div>
  )
}
